"""
Competitive Reports models for the enhanced competitive analysis system.

This module defines database models for:
1. CompetitorFunctionalReport - Per-competitor functional audit reports
2. CompetitorAlert - Competitor change alerts

Cross-competitor synthesis is now handled by the unified SynthesisReport
in app.models.synthesis (Phase 3+).
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Text, DateTime, ForeignKey,
    JSON, Boolean
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.database import Base


class CompetitorFunctionalReport(Base):
    """
    Per-competitor functional audit report.

    Generated by the CompetitorFunctionalAuditAgent using the
    Competitor_Functional_Audit_Prompt.md template.

    Contains:
    - Competitor context (positioning, differentiation, target customer)
    - Functional comparison table (feature mapping: Parity/Advantage/Gap/Differentiator)
    - Deep-dive on gaps (user problems, evidence)
    - Technical constraints (integrations, API, platform requirements)
    """
    __tablename__ = "competitor_functional_reports"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    product_competitor_id = Column(
        Integer,
        ForeignKey("product_competitors.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    product_id = Column(
        Integer,
        ForeignKey("ci_products.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Report version (increments with each new report)
    report_version = Column(Integer, nullable=False, default=1)

    # Full markdown report content (for display and export)
    report_content_md = Column(Text, nullable=True)

    # Structured sections for querying
    # Section 0: Competitor context
    # {positioning: str, core_differentiation: str, target_customer: str}
    competitor_context = Column(JSON, nullable=True)

    # Section 1: Functional comparison table
    # [{feature_category, competitor_feature_name, functional_description, mapping_status}]
    functional_comparison = Column(JSON, nullable=True)

    # Section 2: Deep-dive on gaps
    # [{feature_name, user_problem, evidence}]
    gaps_deep_dive = Column(JSON, nullable=True)

    # Section 3: Technical constraints
    # {integrations: [], api_capabilities: str, platform_requirements: str}
    technical_constraints = Column(JSON, nullable=True)

    # Unified per-job comparison (replaces gaps_deep_dive)
    # [{job_id, job_statement, importance, our_score, competitor_score, score_rationale,
    #   features: [{feature_name, description, whose, position, evidence_ids}],
    #   outcome_coverage: [{desired_outcome, our_coverage, competitor_coverage}]}]
    job_assessments = Column(JSON, nullable=True)

    # Evidence citation tracking: [{evidence_id, finding_type, finding_description}]
    evidence_citations = Column(JSON, nullable=True)

    # Competitor capabilities that fit no job in our map:
    # [{capability, why_unmapped, suggested_job_statement}]
    #
    # The job map is generated from our own product description, so it cannot contain
    # jobs we never addressed — which is where opportunity hides. A competitor serving
    # a job the map lacks is evidence the map is incomplete, and it arrives free with an
    # audit already being run. Kept rather than discarded so audits become a passive
    # source of job discovery independent of our own product copy.
    unmapped_capabilities = Column(JSON, nullable=True)

    # Raw search results used (cleaned HTML, for reference)
    raw_search_results = Column(JSON, nullable=True)

    # Structured diff from previous version
    changes_from_previous = Column(JSON, nullable=True)

    # Timestamps
    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Queue job reference
    queue_job_id = Column(Integer, ForeignKey("queue_jobs.id"), nullable=True)

    # Relationships
    competitor = relationship("ProductCompetitor", backref="functional_reports")
    product = relationship("CIProduct", backref="competitor_functional_reports")

    def __repr__(self):
        return f"<CompetitorFunctionalReport(id={self.id}, competitor_id={self.product_competitor_id}, version={self.report_version})>"

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "product_competitor_id": self.product_competitor_id,
            "product_id": self.product_id,
            "report_version": self.report_version,
            "report_content_md": self.report_content_md,
            "competitor_context": self.competitor_context,
            "functional_comparison": self.functional_comparison,
            "gaps_deep_dive": self.gaps_deep_dive,
            "technical_constraints": self.technical_constraints,
            "job_assessments": self.job_assessments,
            "evidence_citations": self.evidence_citations,
            "unmapped_capabilities": self.unmapped_capabilities,
            "changes_from_previous": self.changes_from_previous,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "queue_job_id": self.queue_job_id,
        }


class ProductSelfAssessment(Base):
    """How well our own product serves each job in the map.

    Deliberately shaped like CompetitorFunctionalReport: a self-assessment is an audit
    whose subject is us. Same job-keyed structure, same evidence citations, same
    versioning — which is what lets a comparison view put us in a column beside the
    competitors with no special-casing, and lets our score inherit the change detection
    and review machinery built for competitor reports.

    Assessed once per product rather than re-derived inside each competitor audit, where
    the same job could otherwise carry a different "our" score in every report.
    """
    __tablename__ = "product_self_assessments"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    product_id = Column(
        Integer,
        ForeignKey("ci_products.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Increments with each re-assessment, mirroring CompetitorFunctionalReport
    assessment_version = Column(Integer, nullable=False, default=1)

    # Which job map this was assessed against. A restated job makes the assessment of it
    # incomparable to later ones, the same way it does for competitor reports.
    job_map_version = Column(Integer, nullable=True)

    # [{job_id, job_statement, importance, score, confidence, score_rationale,
    #   features: [...], outcome_coverage: [...], evidence_ids: [...]}]
    job_assessments = Column(JSON, nullable=True)

    # False when nothing but the product's own description was available. Recorded rather
    # than inferred because it changes how every score should be read: the job map is
    # generated from that same description, so scoring against it without independent
    # evidence is circular.
    evidence_based = Column(Boolean, nullable=False, default=False, server_default='0')

    assessment_summary = Column(Text, nullable=True)

    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    queue_job_id = Column(Integer, ForeignKey("queue_jobs.id"), nullable=True)

    product = relationship("CIProduct", backref="self_assessments")

    def __repr__(self):
        return (
            f"<ProductSelfAssessment(id={self.id}, product_id={self.product_id}, "
            f"v={self.assessment_version}, evidence_based={self.evidence_based})>"
        )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "product_id": self.product_id,
            "assessment_version": self.assessment_version,
            "job_map_version": self.job_map_version,
            "job_assessments": self.job_assessments,
            "evidence_based": self.evidence_based,
            "assessment_summary": self.assessment_summary,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
        }


class CompetitorAlert(Base):
    """
    Tracks alerts for competitor changes.

    Generated during market discovery when:
    - New competitors are discovered (if alert_on_new_competitors enabled)
    - Known competitors disappear (if alert_on_disappeared_competitors enabled)
    """
    __tablename__ = "competitor_alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    product_id = Column(
        Integer,
        ForeignKey("ci_products.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Alert type: "new_competitor", "competitor_disappeared", "competitor_change"
    alert_type = Column(String(50), nullable=False)

    # Reference to competitor (nullable for disappeared competitors)
    competitor_id = Column(
        Integer,
        ForeignKey("product_competitors.id", ondelete="SET NULL"),
        nullable=True
    )

    # Competitor name (stored separately for display even if competitor deleted)
    competitor_name = Column(String(255), nullable=False)

    # Alert message
    message = Column(Text, nullable=False)

    # Read status
    is_read = Column(Boolean, nullable=False, default=False)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    product = relationship("CIProduct", backref="competitor_alerts")
    competitor = relationship("ProductCompetitor", backref="alerts")

    def __repr__(self):
        return f"<CompetitorAlert(id={self.id}, type={self.alert_type}, competitor={self.competitor_name})>"

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "product_id": self.product_id,
            "alert_type": self.alert_type,
            "competitor_id": self.competitor_id,
            "competitor_name": self.competitor_name,
            "message": self.message,
            "is_read": self.is_read,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
