"""
Competitive Reports models for the enhanced competitive analysis system.

This module defines database models for:
1. CompetitorFunctionalReport - Per-competitor functional audit reports
2. LandscapeOpportunityReport - Cross-competitor landscape synthesis reports

These reports replace the previous multi-table strategic analysis approach
(pricing, positioning, momentum, changes, financials) with a two-step
prompt-based analysis workflow.
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, String, Text, DateTime, ForeignKey,
    JSON, Boolean
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.database import Base


class CompetitorFunctionalReport(Base):
    """
    Per-competitor functional audit report.

    Generated by the CompetitorFunctionalAuditAgent using the
    Competitor_Functional_Audit_Prompt.md template.

    Contains:
    - Competitor context (positioning, differentiation, target customer)
    - Functional comparison table (feature mapping: Parity/Advantage/Gap/Differentiator)
    - Deep-dive on gaps (user problems, evidence)
    - Technical constraints (integrations, API, platform requirements)
    """
    __tablename__ = "competitor_functional_reports"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    product_competitor_id = Column(
        Integer,
        ForeignKey("product_competitors.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    product_id = Column(
        Integer,
        ForeignKey("ci_products.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Report version (increments with each new report)
    report_version = Column(Integer, nullable=False, default=1)

    # Full markdown report content (for display and export)
    report_content_md = Column(Text, nullable=True)

    # Structured sections for querying
    # Section 0: Competitor context
    # {positioning: str, core_differentiation: str, target_customer: str}
    competitor_context = Column(JSON, nullable=True)

    # Section 1: Functional comparison table
    # [{feature_category, competitor_feature_name, functional_description, mapping_status}]
    functional_comparison = Column(JSON, nullable=True)

    # Section 2: Deep-dive on gaps
    # [{feature_name, user_problem, evidence}]
    gaps_deep_dive = Column(JSON, nullable=True)

    # Section 3: Technical constraints
    # {integrations: [], api_capabilities: str, platform_requirements: str}
    technical_constraints = Column(JSON, nullable=True)

    # Raw search results used (cleaned HTML, for reference)
    raw_search_results = Column(JSON, nullable=True)

    # Timestamps
    generated_at = Column(DateTime, server_default=func.now(), nullable=False)

    # Queue job reference
    queue_job_id = Column(Integer, ForeignKey("queue_jobs.id"), nullable=True)

    # Relationships
    competitor = relationship("ProductCompetitor", backref="functional_reports")
    product = relationship("CIProduct", backref="competitor_functional_reports")

    def __repr__(self):
        return f"<CompetitorFunctionalReport(id={self.id}, competitor_id={self.product_competitor_id}, version={self.report_version})>"

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "product_competitor_id": self.product_competitor_id,
            "product_id": self.product_id,
            "report_version": self.report_version,
            "report_content_md": self.report_content_md,
            "competitor_context": self.competitor_context,
            "functional_comparison": self.functional_comparison,
            "gaps_deep_dive": self.gaps_deep_dive,
            "technical_constraints": self.technical_constraints,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "queue_job_id": self.queue_job_id,
        }


class LandscapeOpportunityReport(Base):
    """
    Cross-competitor landscape opportunity synthesis report.

    Generated by the LandscapeOpportunitySynthesizerAgent using the
    Landscape_Opportunity_Synthesizer_Prompt.md template.

    Aggregates all competitor functional reports into:
    - Feature cluster matrix (prevalence across landscape)
    - Feature opportunities (JSON array for idea creation or export)
    - High-impact gaps (top 3 with market gravity)
    """
    __tablename__ = "landscape_opportunity_reports"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    product_id = Column(
        Integer,
        ForeignKey("ci_products.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # Only one report per product (latest)
        index=True
    )

    # Report version (increments with each new report)
    report_version = Column(Integer, nullable=False, default=1)

    # Full markdown report content (for display and export)
    report_content_md = Column(Text, nullable=True)

    # Section 1: Feature cluster matrix
    # [{feature_category, prevalence, our_status, competitors_with_feature}]
    feature_cluster_matrix = Column(JSON, nullable=True)

    # Section 2: Feature opportunities (portable JSON format)
    # [{feature_name, summary, user_value, market_context, priority_score, competitors_with_feature, source_evidence}]
    feature_opportunities = Column(JSON, nullable=True)

    # Section 3: High-impact gaps
    # [{rank, feature_name, market_gravity, competitors_with_feature, user_demand_evidence}]
    high_impact_gaps = Column(JSON, nullable=True)

    # Source competitor reports used for this synthesis
    source_competitor_report_ids = Column(JSON, nullable=True)

    # Timestamps
    generated_at = Column(DateTime, server_default=func.now(), nullable=False)

    # Queue job reference
    queue_job_id = Column(Integer, ForeignKey("queue_jobs.id"), nullable=True)

    # Relationship
    product = relationship("CIProduct", backref="landscape_opportunity_report")

    def __repr__(self):
        return f"<LandscapeOpportunityReport(id={self.id}, product_id={self.product_id}, version={self.report_version})>"

    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "product_id": self.product_id,
            "report_version": self.report_version,
            "report_content_md": self.report_content_md,
            "feature_cluster_matrix": self.feature_cluster_matrix,
            "feature_opportunities": self.feature_opportunities,
            "high_impact_gaps": self.high_impact_gaps,
            "source_competitor_report_ids": self.source_competitor_report_ids,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "queue_job_id": self.queue_job_id,
        }

    def get_portable_export(self, product_name: str = None) -> dict:
        """
        Generate portable JSON export format for use in other systems.

        This format is designed to be tool-agnostic and can be imported
        into various customer voting and roadmap tools.
        """
        return {
            "version": "1.0",
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "product_id": self.product_id,
            "product_name": product_name,
            "feature_ideas": self.feature_opportunities or [],
            "metadata": {
                "total_competitors_analyzed": len(self.source_competitor_report_ids or []),
                "report_ids": self.source_competitor_report_ids,
                "report_version": self.report_version,
            }
        }
