"""
Job map provenance and corroboration.

Two questions about a job look similar and are not the same:

  "Where did this job come from?"  → entry provenance, stored on ProductJob.
  "What establishes it is real?"   → corroboration, derived here.

Only the first needs a column. Evidence, Idea, WinLossTheme and SupportTheme all carry
`job_id_key`, so every signal linked to a job is already evidence for it — making
corroboration a query that self-updates as signals arrive, with no write path to keep
current.

Both matter, for different reasons. Entry measures **circularity**: a job extracted from the
product's own description, with nothing independent supporting it, was derived from what the
product already does — which makes a high coverage score near-tautological and hides the jobs
nobody built for. Linkage cannot tell you that, because it does not know where a job came
from.

Corroboration establishes a job **is real**. It says nothing about whether the statement is
worded *correctly* — a dozen support themes can link to a badly phrased job. That is what
`validation_state` tracks.
"""

from typing import Any, Dict, List, Optional

from sqlalchemy import func as sa_func
from sqlalchemy.orm import Session

from app.models.competitor_intelligence import (
    JOB_PROVENANCE_INDEPENDENT,
    ProductJob,
)
from app.models.evidence import Evidence
from app.models.idea import Idea
from app.models.internal_feedback import SupportTheme, WinLossTheme
from app.models.synthesis import SynthesizedOpportunity

# Signals that independently corroborate a job. Ideas are filtered to active rows —
# a soft-deleted idea is not evidence of anything.
_INDEPENDENT_SOURCES = (
    ("ideas", Idea, (Idea.is_active == True,)),  # noqa: E712 — SQLAlchemy needs ==
    ("evidence", Evidence, ()),
    ("win_loss_themes", WinLossTheme, ()),
    ("support_themes", SupportTheme, ()),
)

# SynthesizedOpportunity also carries job_id_key but is generated by synthesis *from* the
# sources above, so counting it as corroboration would support a job with a restatement of
# its own evidence. It is included only where the caller wants total linkage rather than
# independent support.
_DERIVED_SOURCES = (
    ("opportunities", SynthesizedOpportunity, ()),
)


def signal_counts(
    db: Session,
    product_id: int,
    include_derived: bool = False,
) -> Dict[str, Dict[str, int]]:
    """Count signals linked to each job, keyed by job_id_key.

    Returns {job_id_key: {source_label: count, ..., "total": n}}. Jobs with no linked
    signals are absent rather than zero-filled; treat a missing key as uncorroborated.

    `include_derived` adds synthesis opportunities — appropriate for "how much is attached
    to this job" displays, wrong for judging whether a job is independently supported.
    """
    sources = _INDEPENDENT_SOURCES + (_DERIVED_SOURCES if include_derived else ())
    counts: Dict[str, Dict[str, int]] = {}

    for label, model, extra_filters in sources:
        rows = (
            db.query(model.job_id_key, sa_func.count(model.id))
            .filter(
                model.product_id == product_id,
                model.job_id_key.isnot(None),
                *extra_filters,
            )
            .group_by(model.job_id_key)
            .all()
        )
        for job_id_key, count in rows:
            if not job_id_key:
                continue
            entry = counts.setdefault(job_id_key, {})
            entry[label] = entry.get(label, 0) + count
            entry["total"] = entry.get("total", 0) + count

    return counts


def jobs_with_human_verdict(db: Session, product_id: int) -> set:
    """Jobs a person has judged the competitive position on.

    A PM asserting "we differentiate here" is applying knowledge the product description
    does not contain — and, within a JTBD frame, presupposing the job is real. You cannot
    meaningfully claim differentiation on a need nobody has. So the assertion counts as
    independent support for the job itself, not only for the comparison.
    """
    from app.models.competitive_reports import CompetitorFunctionalReport

    reports = db.query(CompetitorFunctionalReport).filter(
        CompetitorFunctionalReport.product_id == product_id
    ).all()

    return {
        entry["job_id"]
        for report in reports
        for entry in (report.job_assessments or [])
        if isinstance(entry, dict) and entry.get("job_id") and entry.get("human_position")
    }


def has_independent_support(
    job: ProductJob,
    corroboration: Optional[Dict[str, int]],
    human_verdict: bool = False,
) -> bool:
    """Whether anything other than the product's own description supports this job.

    True when the job entered the map from an independent source, when any signal has
    since linked to it, or when a person has judged its competitive position. A job whose provenance is unknown (predating tracking) counts as
    unsupported unless signals corroborate it — the honest reading, since we cannot claim
    an origin we never recorded.
    """
    if human_verdict:
        return True
    provenance = job.provenance or {}
    if provenance.get("type") in JOB_PROVENANCE_INDEPENDENT:
        return True
    return bool(corroboration and corroboration.get("total", 0) > 0)


def map_health(db: Session, product_id: int) -> Dict[str, Any]:
    """Summarize how circular a product's job map is.

    The headline number is the share of jobs with at least one non-product source. A map
    scoring low can still be correct, but its coverage scores are self-referential and
    should be read that way.
    """
    jobs: List[ProductJob] = (
        db.query(ProductJob)
        .filter(
            ProductJob.product_id == product_id,
            ProductJob.status == "active",
        )
        .all()
    )

    counts = signal_counts(db, product_id)
    judged = jobs_with_human_verdict(db, product_id)

    by_provenance: Dict[str, int] = {}
    supported = 0
    unvalidated = 0
    out_of_target = 0
    human_judged = 0

    for job in jobs:
        provenance_type = (job.provenance or {}).get("type") or "unknown"
        by_provenance[provenance_type] = by_provenance.get(provenance_type, 0) + 1

        if job.job_id_key in judged:
            human_judged += 1

        if has_independent_support(
            job, counts.get(job.job_id_key), job.job_id_key in judged
        ):
            supported += 1
        if job.validation_state == "unvalidated":
            unvalidated += 1
        if job.serve_intent == "out_of_target":
            out_of_target += 1

    total = len(jobs)
    return {
        "total_jobs": total,
        "jobs_with_independent_source": supported,
        # None rather than 0 for an empty map: "0% supported" reads as a failing map when
        # the truth is that there is no map yet.
        "independent_source_pct": round(100 * supported / total) if total else None,
        "by_provenance": by_provenance,
        "unvalidated": unvalidated,
        "out_of_target": out_of_target,
        "human_judged": human_judged,
    }
